###############################################################################
# Client-side reporting
#
# Reports contain federated aggregate results and formula documentation. They do
# not contain supplier raw activity rows.
###############################################################################

write_federated_report <- function(result, output_dir) {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  if (!is.null(result$comparison)) {
    utils::write.csv(
      result$comparison,
      file.path(output_dir, "centralised_federated_comparison.csv"),
      row.names = FALSE
    )
  }

  federated <- result$federated
  formula <- result$formula

  report <- c(
    "# Federated Scope 3 analysis",
    "",
    "This report was generated by `scope3federatedclient` from supplier API aggregate responses.",
    "",
    "## Emission calculation",
    "",
    paste0("- Local record formula: `", formula$local_record_formula, "`"),
    paste0("- Federated mean formula: `", formula$federated_mean_formula, "`"),
    paste0("- Federated sample variance formula: `", formula$federated_sample_variance_formula, "`"),
    "",
    "## Federated results",
    "",
    paste0("- Record count: ", federated$record_count),
    paste0("- Total emissions: ", format(federated$total_emissions_tco2e, digits = 12), " tCO2e"),
    paste0("- Mean emissions: ", format(federated$mean_emissions_tco2e, digits = 12), " tCO2e per record"),
    paste0("- Sample variance: ", format(federated$sample_variance_emissions_tco2e2, digits = 12)),
    "",
    "## Privacy boundary",
    "",
    "The client receives aggregate outputs only. It does not receive invoice-level records, site-level records, raw activity quantities, or invoice references."
  )

  writeLines(report, file.path(output_dir, "federated_report.md"))

  invisible(
    list(
      report_path = file.path(output_dir, "federated_report.md"),
      comparison_path = if (!is.null(result$comparison)) {
        file.path(output_dir, "centralised_federated_comparison.csv")
      } else {
        NULL
      }
    )
  )
}
